language: java
sudo: false

jdk:
  - openjdk7
  - oraclejdk8

install: cd sevntu-checks && mvn clean verify
      && cd ../eclipsecs-sevntu-plugin && mvn verify
      && cd ../sevntu-checkstyle-maven-plugin && mvn verify
      && cd ../sevntu-checkstyle-idea-extension && mvn verify
      && cd ../sevntu-checkstyle-sonar-plugin && mvn verify

after_success:
  - mvn jacoco:report coveralls:jacoco 

cache:
  directories:
  - ~/.m2

branches:
  only:
    - master

matrix:
  fast_finish: true