language: java
sudo: false

jdk:
  - openjdk7
  - oraclejdk8

before_install: git clone git://git.code.sf.net/p/eclipse-cs/git eclipse-cs-git
      && cd eclipse-cs-git/ && git checkout 6.5.0
      && cd net.sf.eclipsecs.parent/ && mvn install

install: cd sevntu-checks && mvn clean verify
      && cd ../eclipsecs-sevntu-plugin && mvn verify
      && cd ../sevntu-checkstyle-maven-plugin && mvn verify
      && cd ../sevntu-checkstyle-idea-extension && mvn verify
      && cd ../sevntu-checkstyle-sonar-plugin && mvn verify

after_success:
  - mvn jacoco:report coveralls:jacoco 

cache:
  directories:
  - ~/.m2

branches:
  only:
    - master

matrix:
  fast_finish: true